# This file is machine-generated - editing it directly is not advised

[[Eterm]]
git-tree-sha1 = "cbc2b764e8da9153d221f36a81f66b8eb7208538"
repo-rev = "master"
repo-url = "https://github.com/helgee/Eterm.jl"
uuid = "31f415ca-2d2d-11e9-05ad-e37ee3ba8a1a"
version = "0.1.0"
